// 全局配置
const CONFIG = {
    APP_NAME: '碗秤铁记录本',
    VERSION: '1.0.0',
    STORAGE_KEYS: {
        USERS: 'wancheng_users',
        CURRENT_USER: 'wancheng_current_user',
        PREMIUM: 'wancheng_premium',
        PREMIUM_EXPIRY: 'wancheng_premium_expiry',
        PREMIUM_PLAN: 'wancheng_premium_plan',
        USED_CODES: 'wancheng_used_codes'
    },
    // 联系方式（购买后联系此微信获取激活码）
    CONTACT_WECHAT: 'rx101022',   // ← 改成你的微信号
    // 激活码池（格式：'CODE': { plan: '套餐key', days: 有效天数 }）
    // 在这里添加更多激活码发给用户
    ACTIVATION_CODES: {
        // 原始激活码（已发出的码保留）
        'WCT-NB-ABCD1': { plan: 'newbie',    days: 1,   name: '新人单次卡' },
        'WCT-NB-ABCD2': { plan: 'newbie',    days: 1,   name: '新人单次卡' },
        'WCT-WK-BCDE1': { plan: 'lifetime', days: -1,  name: '永久会员' },
        'WCT-WK-BCDE2': { plan: 'lifetime', days: -1,  name: '永久会员' },
        'WCT-MO-CDEF1': { plan: 'monthly',  days: 30,  name: '月卡' },
        'WCT-MO-CDEF2': { plan: 'monthly',  days: 30,  name: '月卡' },
        'WCT-QT-DEFG1': { plan: 'quarterly', days: 90,  name: '季卡' },
        'WCT-QT-DEFG2': { plan: 'quarterly', days: 90,  name: '季卡' },
        'WCT-HY-EFGH1': { plan: 'yearly',   days: 365, name: '年卡' },
        'WCT-HY-EFGH2': { plan: 'yearly',   days: 365, name: '年卡' },
        'WCT-YR-FGHI1': { plan: 'yearly',   days: 365, name: '年卡' },
        'WCT-YR-FGHI2': { plan: 'yearly',   days: 365, name: '年卡' },
        // 新增激活码
        'WCT-NB-EXOI1': { plan: 'newbie',    days: 1,   name: '新人单次卡' },
        'WCT-NB-EXOI2': { plan: 'newbie',    days: 1,   name: '新人单次卡' },
        'WCT-NB-XHYR1': { plan: 'newbie',    days: 1,   name: '新人单次卡' },
        'WCT-NB-XHYR2': { plan: 'newbie',    days: 1,   name: '新人单次卡' },
        'WCT-NB-NKER1': { plan: 'newbie',    days: 1,   name: '新人单次卡' },
        'WCT-NB-NKER2': { plan: 'newbie',    days: 1,   name: '新人单次卡' },
        'WCT-NB-RGCG1': { plan: 'newbie',    days: 1,   name: '新人单次卡' },
        'WCT-NB-RGCG2': { plan: 'newbie',    days: 1,   name: '新人单次卡' },
        'WCT-NB-IPGX1': { plan: 'newbie',    days: 1,   name: '新人单次卡' },
        'WCT-NB-IPGX2': { plan: 'newbie',    days: 1,   name: '新人单次卡' },
        'WCT-NB-SYZV1': { plan: 'newbie',    days: 1,   name: '新人单次卡' },
        'WCT-NB-SYZV2': { plan: 'newbie',    days: 1,   name: '新人单次卡' },
        'WCT-NB-KVSF1': { plan: 'newbie',    days: 1,   name: '新人单次卡' },
        'WCT-NB-KVSF2': { plan: 'newbie',    days: 1,   name: '新人单次卡' },
        'WCT-NB-RBUM1': { plan: 'newbie',    days: 1,   name: '新人单次卡' },
        'WCT-NB-RBUM2': { plan: 'newbie',    days: 1,   name: '新人单次卡' },
        'WCT-NB-AUTJ1': { plan: 'newbie',    days: 1,   name: '新人单次卡' },
        'WCT-NB-AUTJ2': { plan: 'newbie',    days: 1,   name: '新人单次卡' },
        'WCT-NB-VROW1': { plan: 'newbie',    days: 1,   name: '新人单次卡' },
        'WCT-NB-VROW2': { plan: 'newbie',    days: 1,   name: '新人单次卡' },
        'WCT-WK-SMAX1': { plan: 'lifetime', days: -1,  name: '永久会员' },
        'WCT-WK-SMAX2': { plan: 'lifetime', days: -1,  name: '永久会员' },
        'WCT-WK-CWIW1': { plan: 'lifetime', days: -1,  name: '永久会员' },
        'WCT-WK-CWIW2': { plan: 'lifetime', days: -1,  name: '永久会员' },
        'WCT-WK-ZMDD1': { plan: 'lifetime', days: -1,  name: '永久会员' },
        'WCT-WK-ZMDD2': { plan: 'lifetime', days: -1,  name: '永久会员' },
        'WCT-WK-OQZB1': { plan: 'lifetime', days: -1,  name: '永久会员' },
        'WCT-WK-OQZB2': { plan: 'lifetime', days: -1,  name: '永久会员' },
        'WCT-WK-ZEPJ1': { plan: 'lifetime', days: -1,  name: '永久会员' },
        'WCT-WK-ZEPJ2': { plan: 'lifetime', days: -1,  name: '永久会员' },
        'WCT-WK-MIMZ1': { plan: 'lifetime', days: -1,  name: '永久会员' },
        'WCT-WK-MIMZ2': { plan: 'lifetime', days: -1,  name: '永久会员' },
        'WCT-WK-WNHU1': { plan: 'lifetime', days: -1,  name: '永久会员' },
        'WCT-WK-WNHU2': { plan: 'lifetime', days: -1,  name: '永久会员' },
        'WCT-WK-NRXZ1': { plan: 'lifetime', days: -1,  name: '永久会员' },
        'WCT-WK-NRXZ2': { plan: 'lifetime', days: -1,  name: '永久会员' },
        'WCT-WK-WBIL1': { plan: 'lifetime', days: -1,  name: '永久会员' },
        'WCT-WK-WBIL2': { plan: 'lifetime', days: -1,  name: '永久会员' },
        'WCT-WK-NZPD1': { plan: 'lifetime', days: -1,  name: '永久会员' },
        'WCT-WK-NZPD2': { plan: 'lifetime', days: -1,  name: '永久会员' },
        'WCT-MO-YWTN1': { plan: 'monthly',    days: 30,   name: '月卡' },
        'WCT-MO-YWTN2': { plan: 'monthly',    days: 30,   name: '月卡' },
        'WCT-MO-WJUQ1': { plan: 'monthly',    days: 30,   name: '月卡' },
        'WCT-MO-WJUQ2': { plan: 'monthly',    days: 30,   name: '月卡' },
        'WCT-MO-JSKH1': { plan: 'monthly',    days: 30,   name: '月卡' },
        'WCT-MO-JSKH2': { plan: 'monthly',    days: 30,   name: '月卡' },
        'WCT-MO-HYIH1': { plan: 'monthly',    days: 30,   name: '月卡' },
        'WCT-MO-HYIH2': { plan: 'monthly',    days: 30,   name: '月卡' },
        'WCT-MO-FAKU1': { plan: 'monthly',    days: 30,   name: '月卡' },
        'WCT-MO-FAKU2': { plan: 'monthly',    days: 30,   name: '月卡' },
        'WCT-MO-SOUY1': { plan: 'monthly',    days: 30,   name: '月卡' },
        'WCT-MO-SOUY2': { plan: 'monthly',    days: 30,   name: '月卡' },
        'WCT-MO-FCRP1': { plan: 'monthly',    days: 30,   name: '月卡' },
        'WCT-MO-FCRP2': { plan: 'monthly',    days: 30,   name: '月卡' },
        'WCT-MO-HJEC1': { plan: 'monthly',    days: 30,   name: '月卡' },
        'WCT-MO-HJEC2': { plan: 'monthly',    days: 30,   name: '月卡' },
        'WCT-MO-OSAI1': { plan: 'monthly',    days: 30,   name: '月卡' },
        'WCT-MO-OSAI2': { plan: 'monthly',    days: 30,   name: '月卡' },
        'WCT-MO-CPWW1': { plan: 'monthly',    days: 30,   name: '月卡' },
        'WCT-MO-CPWW2': { plan: 'monthly',    days: 30,   name: '月卡' },
        'WCT-QT-QJWN1': { plan: 'quarterly', days: 90,  name: '季卡' },
        'WCT-QT-QJWN2': { plan: 'quarterly', days: 90,  name: '季卡' },
        'WCT-QT-BLKG1': { plan: 'quarterly', days: 90,  name: '季卡' },
        'WCT-QT-BLKG2': { plan: 'quarterly', days: 90,  name: '季卡' },
        'WCT-QT-STSZ1': { plan: 'quarterly', days: 90,  name: '季卡' },
        'WCT-QT-STSZ2': { plan: 'quarterly', days: 90,  name: '季卡' },
        'WCT-QT-PDDC1': { plan: 'quarterly', days: 90,  name: '季卡' },
        'WCT-QT-PDDC2': { plan: 'quarterly', days: 90,  name: '季卡' },
        'WCT-QT-HNRO1': { plan: 'quarterly', days: 90,  name: '季卡' },
        'WCT-QT-HNRO2': { plan: 'quarterly', days: 90,  name: '季卡' },
        'WCT-QT-EVYA1': { plan: 'quarterly', days: 90,  name: '季卡' },
        'WCT-QT-EVYA2': { plan: 'quarterly', days: 90,  name: '季卡' },
        'WCT-QT-HOFC1': { plan: 'quarterly', days: 90,  name: '季卡' },
        'WCT-QT-HOFC2': { plan: 'quarterly', days: 90,  name: '季卡' },
        'WCT-QT-HIBD1': { plan: 'quarterly', days: 90,  name: '季卡' },
        'WCT-QT-HIBD2': { plan: 'quarterly', days: 90,  name: '季卡' },
        'WCT-QT-HLHO1': { plan: 'quarterly', days: 90,  name: '季卡' },
        'WCT-QT-HLHO2': { plan: 'quarterly', days: 90,  name: '季卡' },
        'WCT-QT-TPCP1': { plan: 'quarterly', days: 90,  name: '季卡' },
        'WCT-QT-TPCP2': { plan: 'quarterly', days: 90,  name: '季卡' },
        'WCT-HY-WXZW1': { plan: 'yearly',   days: 365, name: '年卡' },
        'WCT-HY-WXZW2': { plan: 'yearly',   days: 365, name: '年卡' },
        'WCT-HY-ECVH1': { plan: 'yearly',   days: 365, name: '年卡' },
        'WCT-HY-ECVH2': { plan: 'yearly',   days: 365, name: '年卡' },
        'WCT-HY-CLWP1': { plan: 'yearly',   days: 365, name: '年卡' },
        'WCT-HY-CLWP2': { plan: 'yearly',   days: 365, name: '年卡' },
        'WCT-HY-SWKZ1': { plan: 'yearly',   days: 365, name: '年卡' },
        'WCT-HY-SWKZ2': { plan: 'yearly',   days: 365, name: '年卡' },
        'WCT-HY-ADLE1': { plan: 'yearly',   days: 365, name: '年卡' },
        'WCT-HY-ADLE2': { plan: 'yearly',   days: 365, name: '年卡' },
        'WCT-HY-RSRL1': { plan: 'yearly',   days: 365, name: '年卡' },
        'WCT-HY-RSRL2': { plan: 'yearly',   days: 365, name: '年卡' },
        'WCT-HY-IHDQ1': { plan: 'yearly',   days: 365, name: '年卡' },
        'WCT-HY-IHDQ2': { plan: 'yearly',   days: 365, name: '年卡' },
        'WCT-HY-XVXQ1': { plan: 'yearly',   days: 365, name: '年卡' },
        'WCT-HY-XVXQ2': { plan: 'yearly',   days: 365, name: '年卡' },
        'WCT-HY-YUFS1': { plan: 'yearly',   days: 365, name: '年卡' },
        'WCT-HY-YUFS2': { plan: 'yearly',   days: 365, name: '年卡' },
        'WCT-HY-HSTP1': { plan: 'yearly',   days: 365, name: '年卡' },
        'WCT-HY-HSTP2': { plan: 'yearly',   days: 365, name: '年卡' },
        'WCT-YR-DOKT1': { plan: 'yearly',   days: 365, name: '年卡' },
        'WCT-YR-DOKT2': { plan: 'yearly',   days: 365, name: '年卡' },
        'WCT-YR-OXMI1': { plan: 'yearly',   days: 365, name: '年卡' },
        'WCT-YR-OXMI2': { plan: 'yearly',   days: 365, name: '年卡' },
        'WCT-YR-NSFS1': { plan: 'yearly',   days: 365, name: '年卡' },
        'WCT-YR-NSFS2': { plan: 'yearly',   days: 365, name: '年卡' },
        'WCT-YR-LURH1': { plan: 'yearly',   days: 365, name: '年卡' },
        'WCT-YR-LURH2': { plan: 'yearly',   days: 365, name: '年卡' },
        'WCT-YR-EXXP1': { plan: 'yearly',   days: 365, name: '年卡' },
        'WCT-YR-EXXP2': { plan: 'yearly',   days: 365, name: '年卡' },
        'WCT-YR-IWSE1': { plan: 'yearly',   days: 365, name: '年卡' },
        'WCT-YR-IWSE2': { plan: 'yearly',   days: 365, name: '年卡' },
        'WCT-YR-SDXK1': { plan: 'yearly',   days: 365, name: '年卡' },
        'WCT-YR-SDXK2': { plan: 'yearly',   days: 365, name: '年卡' },
        'WCT-YR-GYSK1': { plan: 'yearly',   days: 365, name: '年卡' },
        'WCT-YR-GYSK2': { plan: 'yearly',   days: 365, name: '年卡' },
        'WCT-YR-BRUW1': { plan: 'yearly',   days: 365, name: '年卡' },
        'WCT-YR-BRUW2': { plan: 'yearly',   days: 365, name: '年卡' },
        'WCT-YR-WWRH1': { plan: 'yearly',   days: 365, name: '年卡' },
        'WCT-YR-WWRH2': { plan: 'yearly',   days: 365, name: '年卡' },
    }
};

// 会员套餐配置
const MEMBERSHIP_PLANS = {
    newbie: { price: 0.1, days: 1, name: '新人单次卡', plan: 'newbie' },
    monthly: { price: 8, days: 30, name: '月卡', plan: 'monthly' },
    quarterly: { price: 18, days: 90, name: '季卡', plan: 'quarterly' },
    yearly: { price: 38, days: 365, name: '年卡', plan: 'yearly' },
    lifetime: { price: 68, days: -1, name: '永久会员', plan: 'lifetime' }
};

// 全局变量
let currentUser = null;
let appData = {
    dietRecords: [],
    trainingRecords: [],
    weightRecords: [],
    userInfo: { nickname: '', gender: '', height: '', avatar: '' },
    isPremium: false,
    currentDate: new Date().toISOString().slice(0, 10)
};